name: SpecialTools
main: Nerahikada\SpecialTools\Main
version: 1.0.0
api: [3.0.0, 3.0.0-ALHPA7, 3.0.0-ALHPA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14]
load: STARTUP
author: ねらひかだ
description: 特別なアイテムを追加します
website: https://twitter.com/Nerahikada